// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_MainWindow.cpp"
#include "UNQDMUN5UU/moc_SerialReader.cpp"
#include "VSCBVMNR7M/moc_DataProcessor.cpp"
#include "RZ4CM6YYJ6/moc_BatteryWidget.cpp"
#include "RZ4CM6YYJ6/moc_RpmGauge.cpp"
#include "RZ4CM6YYJ6/moc_SpeedometerWidget.cpp"
