// This file is autogenerated. Changes will be overwritten.
#include "5Z5WMX6UGY/moc_ILedController.cpp"
#include "5Z5WMX6UGY/moc_IVehicleDataProvider.cpp"
#include "NX6PWWVH4D/moc_MockLedController.cpp"
#include "NX6PWWVH4D/moc_MockVehicleDataProvider.cpp"
#include "NX6PWWVH4D/moc_VSomeIPClient.cpp"
#include "IVK4DJNV27/moc_GearStateManager.cpp"
#include "ULO4IMYJZC/moc_ShellClient.cpp"
